spring:
  application.name: pet-tracker
  profiles:
    active: embedded
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  tracing:
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: embedded
  data:
    mongodb:
      password: a
      username: mongo
      host: localhost
      database: tracker
      port: 27017
logging:
  level:
    de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongo: WARN
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      password: a
      username: mongo
      host: localhost
      database: tracker
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4