spring:
  application.name: pet-tracker
  profiles:
    active: h2
  threads:
    virtual:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:pet_tracker_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never
  jpa:
    show-sql: true