spring:
  application.name: pet-tracker
  profiles:
    active: embedded
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

---
spring:
  config:
    activate:
      on-profile: embedded
  data:
    mongodb:
      password: a
      username: mongo
      host: localhost
      database: tracker
      port: 27017
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      password: a
      username: mongo
      host: localhost
      database: tracker
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4